# Bündelblockausgleichung

Mit Aruco-Markern und Näherungskoordinaten aus GNSS

In [8]:
from PIL import Image
from glob import glob
import cv2
from cv2 import aruco
import numpy as np
from sympy import *
import math
from PIL import ExifTags
from xml.etree import ElementTree as ET
import utm
import math

## Parameter festlegen
Sensorgröße in Millimetern und Pixeln

In [9]:
Xsensor = 0.00617
Ysensor = 0.00455
Xpixel = 4000.
Ypixel = 3000.

In [10]:
bilder = glob('./bildverband2/*.JPG')

bilderDaten = []

for bild in bilder:
    bildDaten = []
    img = Image.open(bild)
    exif = img._getexif()
    for tag, value in exif.items():
        if 'GPSInfo' == ExifTags.TAGS.get(tag, tag):
            n = float(value[2][0])+float(value[2][1]) / \
                60.+float(value[2][2])/3600.
            e = float(value[4][0])+float(value[4][1]) / \
                60.+float(value[4][2])/3600.
            h = float(value[6])
            u = utm.from_latlon(n,e, 32)
            bildDaten.append(u[0])
            bildDaten.append(u[1])
            bildDaten.append(h)
    with open(bild, "rb") as f:
        s = str(f.read())

    start = s.find('<x:xmpmeta')
    end = s.find('</x:xmpmeta')
    xmp = s[start:end+12].replace("\\n", "\n")
    tree = ET.XML(xmp)

    bildDaten.append(float(tree[0][0].attrib['{http://www.dji.com/drone-dji/1.0/}FlightRollDegree'])/180*math.pi)
   
    bildDaten.append(float(
        tree[0][0].attrib['{http://www.dji.com/drone-dji/1.0/}FlightPitchDegree'])/180*math.pi)
    bildDaten.append(float(
        tree[0][0].attrib['{http://www.dji.com/drone-dji/1.0/}FlightYawDegree'])/180*math.pi)
    #bildDaten.append(float(tree[0][0].attrib['{http://www.dji.com/drone-dji/1.0/}RelativeAltitude'])/180*math.pi)
    bilderDaten.append(bildDaten)
bilderDaten = np.array(bilderDaten)


## Marker identifizieren

In [11]:

LUT_IN = [0, 158, 216, 255]
LUT_OUT = [0, 22, 80, 176]
lut = np.interp(np.arange(0, 256),
                LUT_IN, LUT_OUT).astype(np.uint8)

aruco_dict = aruco.Dictionary_create(32, 3)
beobachtungen = []

markers = set()
for bildnr in range(len(bilder)):
    bild = bilder[bildnr]
    cv_img = cv2.imread(bild)
    tmp = cv2.LUT(cv_img, lut)
    gray = cv2.cvtColor(tmp, cv2.COLOR_BGR2GRAY)
    
    parameter = aruco.DetectorParameters.create()
    parameter.cornerRefinementMethod = aruco.CORNER_REFINE_SUBPIX;
    corners, ids, _ = aruco.detectMarkers(gray, aruco_dict, parameters=parameter)

    for nr in range(len(ids)):
        for cid in range(len(corners[nr][0])):
            markers.add(ids[nr][0]*10 + cid)
            beobachtungen.append(
                (bildnr, ids[nr][0]*10 + cid, 0, (corners[nr][0][cid][0]/Xpixel-0.5)*Xsensor))
            beobachtungen.append(
                    (bildnr, ids[nr][0]*10 + cid, 1, (corners[nr][0][cid][1]/Ypixel-0.5)*Ysensor))

    #marked = aruco.drawDetectedMarkers(cv_img, corners, ids)
    #cv2.imshow('image', cv2.resize(marked, (800,600)))
    # cv2.waitKey(0)

## Vektor mit Beobachtungen
Erstmal nur Marker aus den Bildern, wird noch mit weiteren Daten gefüllt

In [12]:

l = [i[len(i)-1] for i in beobachtungen]


## Festlegen von Symbolen
für die Unbekannten

In [13]:
sym = []

innereOrientierung = [
    Symbol('c'),
    Symbol('deltax'),
    Symbol('deltay')
]

sym.extend(innereOrientierung)

bildOrientierung = []
for bild in range(len(bilder)):
    bildO = []
    bildO.append(Symbol('bild'+str(bild)+'_x'))
    bildO.append(Symbol('bild'+str(bild)+'_y'))
    bildO.append(Symbol('bild'+str(bild)+'_z'))
    bildO.append(Symbol('bild'+str(bild)+'_kappa'))
    bildO.append(Symbol('bild'+str(bild)+'_omega'))
    bildO.append(Symbol('bild'+str(bild)+'_phi'))
    bildOrientierung.append(bildO)
    sym.extend(bildO)

neupunkte = []
for marker in list(markers):
    neup = []
    neup.append(Symbol('marker'+str(marker)+'x'))
    neup.append(Symbol('marker'+str(marker)+'y'))
    neup.append(Symbol('marker'+str(marker)+'z'))
    neupunkte.append(neup)
    sym.extend(neup)

print(sym)


[c, deltax, deltay, bild0_x, bild0_y, bild0_z, bild0_kappa, bild0_omega, bild0_phi, bild1_x, bild1_y, bild1_z, bild1_kappa, bild1_omega, bild1_phi, bild2_x, bild2_y, bild2_z, bild2_kappa, bild2_omega, bild2_phi, bild3_x, bild3_y, bild3_z, bild3_kappa, bild3_omega, bild3_phi, bild4_x, bild4_y, bild4_z, bild4_kappa, bild4_omega, bild4_phi, bild5_x, bild5_y, bild5_z, bild5_kappa, bild5_omega, bild5_phi, marker0x, marker0y, marker0z, marker1x, marker1y, marker1z, marker2x, marker2y, marker2z, marker3x, marker3y, marker3z, marker260x, marker260y, marker260z, marker261x, marker261y, marker261z, marker262x, marker262y, marker262z, marker263x, marker263y, marker263z, marker10x, marker10y, marker10z, marker11x, marker11y, marker11z, marker12x, marker12y, marker12z, marker13x, marker13y, marker13z, marker140x, marker140y, marker140z, marker141x, marker141y, marker141z, marker142x, marker142y, marker142z, marker143x, marker143y, marker143z, marker30x, marker30y, marker30z, marker31x, marker31y, m

## Erzeugen von Näherungswerten
- Brennweite: EXIF
- Verschiebung Fokuspunkt: 0
- Bilder: GNSS aus EXIF, Ausrichtung aus Kompass, Neigung 0
- Marker: Koordinaten des ersten Bildes plus Zufall

In [14]:
from random import random

x0 = []

bilderDatenFlat = bilderDaten.flatten()

for nr, __ in enumerate(sym):
    if nr == 0:  # Brennweite
        x0.append(0.0045)
    elif nr == 1:  # Fokuspunkt
        x0.append(0)
    elif nr == 2:  # Fokuspunkt
        x0.append(0)
    elif nr > 2 and nr < len(bilderDatenFlat)+3:
        x0.append(bilderDatenFlat[nr-3])
    elif (nr-3) % 3 == 0:
        x0.append(bilderDatenFlat[0]+(random()-5)*10)
    elif (nr-3) % 3 == 1:
        x0.append(bilderDatenFlat[1]+(random()-5)*10)
    elif (nr-3) % 3 == 2:
        x0.append(bilderDatenFlat[2]+(random()-5)*10)
    else:
        x0.append(0)


## Formeln
siehe Seite 281 Nahbereichsphotogrammetrie

folgende Formeln aus Nahbereichsphotogrammetrie S. 274

In [15]:
formeln = []


def r11(kappa, omega, phi):
    return cos(phi)*cos(kappa)-sin(phi)*sin(omega)*sin(kappa)


def r21(kappa, omega, phi):
    return sin(phi)*cos(kappa)+cos(phi)*sin(omega)*sin(kappa)


def r31(kappa, omega, phi):
    return -cos(omega)*sin(kappa)


def r12(kappa, omega, phi):
    return -sin(phi)*cos(omega)


def r22(kappa, omega, phi):
    return cos(phi)*cos(omega)


def r32(kappa, omega, phi):
    return sin(omega)


def r13(kappa, omega, phi):
    return cos(phi)*sin(kappa)+sin(phi)*sin(omega)*cos(kappa)


def r23(kappa, omega, phi):
    return sin(phi)*sin(kappa)-cos(phi)*sin(omega)*cos(kappa)


def r33(kappa, omega, phi):
    return cos(omega)*cos(kappa)


def kx(x, x0, y, y0, z, z0, kappa, omega, phi):
    return r11(kappa, omega, phi)*(x-x0)+r21(kappa, omega, phi)*(y-y0)+r31(kappa, omega, phi)*(z-z0)


def ky(x, x0, y, y0, z, z0, kappa, omega, phi):
    return r12(kappa, omega, phi)*(x-x0)+r22(kappa, omega, phi)*(y-y0)+r32(kappa, omega, phi)*(z-z0)


def nenner(x, x0, y, y0, z, z0, kappa, omega, phi):
    return r13(kappa, omega, phi)*(x-x0)+r23(kappa, omega, phi)*(y-y0)+r33(kappa, omega, phi)*(z-z0)


def x_kolinear(c, x, x0, y, y0, z, z0, kappa, omega, phi, deltax):
    return x0+c*kx(x, x0, y, y0, z, z0, kappa, omega, phi)/nenner(x, x0, y, y0, z, z0, kappa, omega, phi) + deltax


def y_kolinear(c, x, x0, y, y0, z, z0, kappa, omega, phi, deltay):
    return y0+c*ky(x, x0, y, y0, z, z0, kappa, omega, phi)/nenner(x, x0, y, y0, z, z0, kappa, omega, phi) + deltay


def kolinear(xy, c, x0, y0, z0, kappa, omega, phi, x, y, z, deltax, deltay):
    if xy == 0:
        return x_kolinear(c, x, x0, y, y0, z, z0, kappa, omega, phi, deltax)
    return y_kolinear(c, x, x0, y, y0, z, z0, kappa, omega, phi, deltay)

In [16]:
formeln = []
for bnr in range(len(beobachtungen)):
    bildnr, punkt, xy, koord = beobachtungen[bnr]
    ori = bildOrientierung[bildnr]
    bo = bildOrientierung[bildnr]
    neup = neupunkte[list(markers).index(punkt)]
    formeln.append(kolinear(
        xy, innereOrientierung[0], bo[0], bo[1], bo[2], bo[3], bo[4], bo[5], neup[0], neup[1], neup[2], innereOrientierung[1],innereOrientierung[2]))


formeln.append(innereOrientierung[0])
l.append(x0[0])

for bild in range(len(bildOrientierung)):
    for bildP in range(3):
        formeln.append(bildOrientierung[bild][bildP])
        l.append(bilderDaten[bild][bildP])


## Bilden der A-Matrix-Vorlage
aus Ableitungen der Formeln

In [17]:
A_vorlage = []
for f in range(len(formeln)):
    zeile = []
    for s in range(len(sym)):
        formel = formeln[f].diff(sym[s])
        zeile.append(formel)
    A_vorlage.append(zeile)


## Gewichtung
erstmal alles gleich

In [18]:

P = np.eye(len(l))
print('P', P)


P [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


## Ab hier Schleife...

In [19]:
werte = {}

for nr in range(len(sym)):
    werte[sym[nr]] = x0[nr]

#print(werte)

A = np.empty((len(formeln), len(sym)))
for f in range(len(formeln)):
    for s in range(len(sym)):
        A[f][s] = A_vorlage[f][s].evalf(subs=werte)


l0 = np.empty(len(l))
for i in range(len(l0)):
    l0[i] = formeln[i].evalf(subs=werte)

dl = l - l0

N = np.transpose(A)@P@A
h = np.transpose(A)@P@dl
Qx = np.linalg.inv(N)
dx = Qx@h

x0 = x0 + dx

#print('x0', x0)

dx.sum()


1.5366143850533953e+27

In [20]:
dx

array([ 3.56152570e+08, -1.10758058e+09, -1.72056862e+09, -4.67932144e+09,
       -1.24866254e+09, -4.73166571e+04, -1.53836557e+12, -1.44489182e+12,
        1.68423466e+12,  6.98863916e+08,  1.51410318e+09,  1.06755403e+05,
        1.43628650e+11,  7.74542257e+10,  1.50154260e+11, -2.73553696e+08,
        1.40296469e+08, -1.48357988e+04,  7.56818744e+12,  4.26762333e+12,
        4.26520302e+12, -3.14961357e+08, -5.94792702e+08, -7.36944711e+04,
        1.13266439e+13,  6.24227084e+12,  6.77987422e+12,  4.60761373e+08,
        4.74837544e+08,  5.93570386e+04,  3.47977677e+12,  4.77995378e+12,
        3.12659236e+12,  4.16482147e+09, -2.76855975e+08, -2.74799511e+04,
        6.57875850e+12,  4.68146400e+12,  4.82536033e+12,  3.63872218e+15,
        3.55396191e+15,  3.44494389e+15,  3.92116378e+15,  3.22403897e+15,
        3.31623070e+15,  4.04519023e+15,  3.43510523e+15,  3.99702505e+15,
        2.18773197e+15,  2.06969044e+15,  2.23850811e+15, -8.50306212e+25,
       -8.34994208e+25, -