In [1]:
import numpy as np

In [7]:
globale = np.array([[3738525.93234692,  652462.93200035, 5109102.83932901],
              [3738526.95143331, 652464.73288259, 5109101.87017219],
              [3738527.4812818, 652458.83939154, 5109103.5996587],
              [3738527.59613748, 652464.82298695, 5109102.75715289],
              [3738527.96513035, 652462.4986026, 5109101.41679758],
              [3738528.27712998, 652461.8470651, 5109102.6396793]])
lokale = np.array([[-4.17630837e-03, -2.81093506e-04, -4.77740430e-03],
              [-9.54267415e-01, -3.51704859e-01, 8.80606506e-01],
              [8.05933711e-01, 3.80201536e-01, 7.76792687e-01],
              [-9.76571611e-01, 1.76687098e-01, 1.02455167e+00],
              [-1.69209390e-02, -2.14627830e-01, 9.77519868e-01],
              [2.81925220e-01, 2.63439559e-01, 7.54269189e-01]])



In [78]:
l = globale.ravel()
l

array([3738525.93234692,  652462.93200035, 5109102.83932901,
       3738526.95143331,  652464.73288259, 5109101.87017219,
       3738527.4812818 ,  652458.83939154, 5109103.5996587 ,
       3738527.59613748,  652464.82298695, 5109102.75715289,
       3738527.96513035,  652462.4986026 , 5109101.41679758,
       3738528.27712998,  652461.8470651 , 5109102.6396793 ])

In [81]:
A = np.zeros((len(l),12))
for p in range(len(lokale)):
    for i in range(3):
        A[p*3+i,i*4:i*4+3] = lokale[p].T
        A[p*3+i, i*4+3] = 1

In [83]:
N = A.T @ A
x = np.linalg.inv(N) @ A.T @ l

In [84]:
R = x.reshape((3,4))

array([[ 4.27088887e-01,  3.79742649e-01,  1.97710811e+00,
         3.73852596e+06],
       [-3.02238471e+00, -5.71158012e-01, -9.32569750e-01,
         6.52462886e+05],
       [-1.75155464e-01,  2.55051464e+00, -6.60012811e-01,
         5.10910287e+06]])

In [85]:
R@np.c_[lokale, np.ones(len(lokale))].T-globale.T

array([[ 0.01617656,  0.20836594,  0.50296471,  0.039384  , -0.16133865,
        -0.60555256],
       [-0.02844028,  0.41725456,  0.66952006, -0.04147215, -0.35015822,
        -0.66670397],
       [ 0.03622391, -0.3088818 , -0.41142073,  0.06070997,  0.26596436,
         0.35740429]])

## Versuche Scherung

In [109]:
from cv2 import Rodrigues

In [113]:
u,s,v = np.linalg.svd(R[:,:3])
u,s,v

(array([[-0.40312395,  0.11665978, -0.90767922],
        [ 0.91481274,  0.02463016, -0.40312654],
        [-0.02467237, -0.99286648, -0.11665086]]),
 array([3.43744296, 2.65093771, 1.64140777]),
 array([[-0.85318195, -0.21484378, -0.47531327],
        [ 0.05631527, -0.94384998,  0.32553925],
        [ 0.5185645 , -0.25097681, -0.81737476]]))

In [116]:
np.linalg.norm(R[:,:3])

4.640873225152347

In [111]:
Rodrigues(R[:,:3])[0]

array([[ 1.32516186],
       [ 1.3225123 ],
       [-1.47822467]])

In [107]:

R2 = Rodrigues(Rodrigues(R[:,:3])[0])[0]
massstab = np.linalg.norm(R[:, :3]@np.array([1, 1, 1])) / \
    np.linalg.norm(R2@np.array([1, 1, 1]))
R3 = np.c_[R2 * massstab, R[:, 3]]
R3@np.c_[lokale, np.ones(len(lokale))].T-globale.T
R2

array([[-0.19435837,  0.95723985, -0.21428183],
       [ 0.10685002, -0.19648806, -0.97466687],
       [-0.97509379, -0.21233068, -0.06409199]])